### ISSUE TITLE
Site Change Suggestions

### ISSUE THREAD

**Issue by JaydenQuallio** [HeathDoMay/heathdomay#1]
- Picture could be brightened
- Picture does not scale with content
- Hamburger is hard to see in desktop view
**- Screen size is hard coded using margin (should use view height and margin auto)**
- Layout of 3D art could be organized more neatly
- Sticky name should have a background color or be non sticky
- For images a carousel could be nice to organize the images better
**- On VR page the Home does not lead to home (lead to index.html instead of home.html)**
- Organize images into a separate folder instead of all in the root

**Comment by HeathDoMay** [comment]
1. I'm deciding to keep the headers at a more muted hue;
2. Picture now scales;
3. Hamburger now has a visible background color;
4. Will do research into a better image display method, I may settle on a grid of some kind and/or an interactive display method;
5. I'm deciding to not change the sticky header's color but instead left align the logo;
6. See 4;
7. The project is organized now.
